"""versão 1

Revision ID: bb25177a7dc2
Revises: 
Create Date: 2021-01-28 12:36:42.841978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb25177a7dc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('card', sa.String(), nullable=True))
    op.add_column('users', sa.Column('dark_mode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dark_mode')
    op.drop_column('users', 'card')
    # ### end Alembic commands ###
